---
title: "Assignment 4"
author: "Haley Grant"
date: "4/25/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
library(sensitivity)
library(tidyverse)
library(pse)
library(readr)
library(janitor)
library(patchwork)
```

```{r}
# read in the function
# I amended Naomi's compute_almond_yield function 
# to calculate the yield and standard deviation
source("R/compute_almond_yield_sd_mean.R")
```

```{r}
# consider the 2 coefficients on precipitation
factors = c("Pcoeff1", "Pcoeff2")

# generate number of sets
# I used the same number given in the example
nsets=100

# assume both parameters have a uniform distribution
q = c("qunif", "qunif")

# assume min values are 20% below default parameter values and 
# assume max values are 20% above default parameter values
p1min = (0.07-(0.07*0.2))
p1max = (0.07+(0.07*0.2))
p2min = (0.0043-(0.0043*0.2))
p2max = (0.0043+(0.0043*0.2))
q.arg = list(list(min=p2min, max=p1max), list(min=p2min, max=p2max))

# generate samples from LHS
sens_almond = LHS(NULL,factors,nsets,q,q.arg)
sens_pars = get.data(sens_almond)

# read in climate data
clim <- read_table2("data/clim.txt") %>% 
  clean_names()

# run model for all parameters generated by LHS
res = sens_pars %>% pmap(compute_almond_yield_sd_mean,clim=clim)

# turn results into dataframe for easy
resd = res %>% map_dfr(`[`,c("meanyield","sdyield"))

# put results in a matrix
sens_almond = pse::tell(sens_almond, t(as.matrix(resd)), res.names=c("meanyield","sdyield"))

# analyze parameter sensitivity
pse::plotscatter(sens_almond, col="blue", cex=5)

# partial rank correlation coefficient (prcc) analysis
pse::plotprcc(sens_almond)
```

It appears that Pcoeff2 contributes more to parameter uncertainty than Pcoeff1. Pcoeff2 has larger PRCC values than Pcoeff 1 for both mean and standard deviation. This outcome makes sense because Pcoeff2 is squared in our function while Pcoeff1 is not. This makes the effect of Pcoeff2 larger on our result.
